import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import dayjs from 'dayjs';
import { Inter } from 'next/font/google';

import theme from '../styles/theme';

import type { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] });

dayjs.locale('ja');

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <head>
        <link rel="icon" href="/icon/icon.svg" sizes="any" />
      </head>

      <AppRouterCacheProvider>
        <ThemeProvider theme={theme}>
          <body className={inter.className}>{children}</body>
        </ThemeProvider>
      </AppRouterCacheProvider>
    </html>
  );
}
