version: "3"
services:
  db:
    image: mysql:8.0
    container_name: ui_personalize_mysql8_0
    volumes:
      - ./lp-generator-db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
